name: Js Unit Tests Linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  jstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Mocha
      run: npm i mocha
    - name: Run Js Tests
      run: npx mocha js/tests.js
    